### GET request to example server
GET 'https://peo4nuh49g.execute-api.us-east-1.amazonaws.com/dev/todos' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFIZUc5UFIyU1d0RVdJeUtvZ0FPZiJ9.eyJpc3MiOiJodHRwczovL2Rldi03djU3dWhvaTV4OHhxMndhLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiIwNU43SXZjd3NWdHI5azF1czNTeU9SVGRBNE5zU2JOa0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9kZXYtN3Y1N3Vob2k1eDh4cTJ3YS51cy5hdXRoMC5jb20vYXBpL3YyLyIsImlhdCI6MTc1NzM4MDQ2NCwiZXhwIjoxNzU3NDY2ODY0LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiIwNU43SXZjd3NWdHI5azF1czNTeU9SVGRBNE5zU2JOayJ9.Pd2TdmhpYjJjRNqMbNb4-KOu9_mwUOFQNJxb428IXvQtc9pAD4RgYfE0mig7SXCTsdfm_kvLazAbrU_J1ZFOcIELjOSH1pjqY9TF062hv0895bWJftkzur5acMQsiK7uCQT4FlKB0VuvVcO5P0jJ9Hinmvja__fdkX-1HccCVkz8F2s-NlSjCjVtaDfYY-x_jbSY511N9IsrByfsO7JpeQ9SNjB5bTlAu3KxSDeNjdCmNtUtg_JP_prZI8y2vV52_VK6UrHH_qu_usLe649d80Lo0z2JM7NxrgZd0mvMCAPUEzJBOI98aREV1FL2V8HZOUq-0htcmCvpPhiy59T1CQ'

###